CREATE TABLE papers_schema.papers
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username             VARCHAR(255)                            NOT NULL,
    type                 VARCHAR(255)                            NOT NULL,
    papers_attributes_id BIGINT,
    report_id            BIGINT,
    CONSTRAINT pk_papers PRIMARY KEY (id)
);

CREATE TABLE papers_schema.papers_attributes
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    size           BIGINT                                  NOT NULL,
    authors        VARCHAR(255),
    hash           VARCHAR(255)                            NOT NULL,
    is_share       BOOLEAN                                 NOT NULL,
    is_source      BOOLEAN                                 NOT NULL,
    created        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    word_count     BIGINT                                  NOT NULL,
    file_name      VARCHAR(255)                            NOT NULL,
    file_extension VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_papers_attributes PRIMARY KEY (id)
);

CREATE TABLE papers_schema.papers_texts
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text        VARCHAR(65000)                          NOT NULL,
    size        BIGINT                                  NOT NULL,
    text_offset BIGINT                                  NOT NULL,
    hash        VARCHAR(255)                            NOT NULL,
    papers_id   BIGINT,
    CONSTRAINT pk_papers_texts PRIMARY KEY (id)
);

CREATE TABLE papers_schema.reports
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type    VARCHAR(255),
    name    VARCHAR(255),
    percent DECIMAL,
    CONSTRAINT pk_reports PRIMARY KEY (id)
);

CREATE TABLE papers_schema.reports_params
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created              TIMESTAMP WITHOUT TIME ZONE,
    updated              TIMESTAMP WITHOUT TIME ZONE,
    original_percentage  DOUBLE PRECISION,
    borrowing_percentage DOUBLE PRECISION,
    citation_percentage  DOUBLE PRECISION,
    end_position         BIGINT,
    check_time           time WITHOUT TIME ZONE,
    report_id            BIGINT,
    CONSTRAINT pk_reports_params PRIMARY KEY (id)
);

CREATE TABLE papers_schema.reports_sources
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_position BIGINT,
    end_position   BIGINT,
    url            VARCHAR(255),
    source_type    VARCHAR(255),
    report_id      BIGINT,
    CONSTRAINT pk_reports_sources PRIMARY KEY (id)
);

ALTER TABLE papers_schema.papers
    ADD CONSTRAINT uc_papers_papers_attributes UNIQUE (papers_attributes_id);

ALTER TABLE papers_schema.papers
    ADD CONSTRAINT uc_papers_report UNIQUE (report_id);

ALTER TABLE papers_schema.reports_params
    ADD CONSTRAINT uc_reports_params_report UNIQUE (report_id);

ALTER TABLE papers_schema.papers
    ADD CONSTRAINT FK_PAPERS_ON_PAPERS_ATTRIBUTES FOREIGN KEY (papers_attributes_id) REFERENCES papers_schema.papers_attributes (id);

ALTER TABLE papers_schema.papers
    ADD CONSTRAINT FK_PAPERS_ON_REPORT FOREIGN KEY (report_id) REFERENCES papers_schema.reports (id);

ALTER TABLE papers_schema.papers_texts
    ADD CONSTRAINT FK_PAPERS_TEXTS_ON_PAPERS FOREIGN KEY (papers_id) REFERENCES papers_schema.papers (id);

CREATE INDEX papers_index ON papers_schema.papers_texts (papers_id);

ALTER TABLE papers_schema.reports_params
    ADD CONSTRAINT FK_REPORTS_PARAMS_ON_REPORT FOREIGN KEY (report_id) REFERENCES papers_schema.reports (id);

ALTER TABLE papers_schema.reports_sources
    ADD CONSTRAINT FK_REPORTS_SOURCES_ON_REPORT FOREIGN KEY (report_id) REFERENCES papers_schema.reports (id);