version: "3.7"
services:
  user_service:
    image: semernik/user-service
    build: ./backend/user-service
    restart: always
    ports:
      - 8080:8080
    networks:
      - postgres-net
    environment:
      - spring.datasource.url=jdbc:postgresql://postgresql:5432/antiplagiat
    depends_on:
      - postgresql
    volumes:
      - .m2:/root/.m2
  
  paper_service:
    image: semernik/paper_service
    build: ./backend/paper-service
    restart: always
    ports:
      - 8081:8082
    networks:
      - postgres-net
    environment:
      - spring.datasource.url=jdbc:postgresql://postgresql:5432/antiplagiat?currentSchema=papers_schema
    depends_on:
      - postgresql
    volumes:
      - .m2:/root/.m2
  
  frond_end:
    image: semernik/fronend
    build: ./client
    restart: always
    ports:
      - 3000:3000

  postgresql:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    networks:
      - postgres-net
    environment:
      POSTGRES_DB : antiplagiat
      POSTGRES_USER :  postgres
      POSTGRES_PASSWORD : postgres
    volumes:
      - local_pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    networks:
      - postgres-net
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin-data:      
      
networks:
  postgres-net: