CREATE TABLE mails
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id      BIGINT,
    text         VARCHAR(255),
    deliver_date TIMESTAMP WITHOUT TIME ZONE,
    status       VARCHAR(255),
    CONSTRAINT pk_mails PRIMARY KEY (id)
);