CREATE TABLE group_group_members
(
    group_id        VARCHAR(255) NOT NULL,
    group_member_id BIGINT       NOT NULL,
    CONSTRAINT pk_group_group_members PRIMARY KEY (group_id, group_member_id)
);

CREATE TABLE group_members
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255)                            NOT NULL,
    email    VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_group_members PRIMARY KEY (id)
);

CREATE TABLE groups
(
    id   VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT pk_groups PRIMARY KEY (id)
);

ALTER TABLE group_members
    ADD CONSTRAINT uc_group_members_email UNIQUE (email);

ALTER TABLE group_members
    ADD CONSTRAINT uc_group_members_username UNIQUE (username);

ALTER TABLE group_group_members
    ADD CONSTRAINT fk_grogromem_on_group FOREIGN KEY (group_id) REFERENCES groups (id);

ALTER TABLE group_group_members
    ADD CONSTRAINT fk_grogromem_on_user FOREIGN KEY (group_member_id) REFERENCES group_members (id);

CREATE TABLE papers
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    owner_name           VARCHAR(255),
    type                 VARCHAR(255)                            NOT NULL,
    papers_attributes_id BIGINT,
    report_id            BIGINT,
    CONSTRAINT pk_papers PRIMARY KEY (id)
);

CREATE TABLE papers_attributes
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text_size  BIGINT                                  NOT NULL,
    authors    VARCHAR(255),
    hash       VARCHAR(255)                            NOT NULL,
    is_shared  BOOLEAN                                 NOT NULL,
    is_source  BOOLEAN                                 NOT NULL,
    created    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    word_count BIGINT                                  NOT NULL,
    name       VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_papers_attributes PRIMARY KEY (id)
);

CREATE TABLE papers_texts
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text      VARCHAR(65000)                          NOT NULL,
    size      BIGINT                                  NOT NULL,
    "offset"  BIGINT                                  NOT NULL,
    hash      VARCHAR(255)                            NOT NULL,
    papers_id BIGINT,
    CONSTRAINT pk_papers_texts PRIMARY KEY (id)
);

CREATE TABLE reports
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type VARCHAR(255),
    name VARCHAR(255),
    CONSTRAINT pk_reports PRIMARY KEY (id)
);

CREATE TABLE reports_params
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created              TIMESTAMP WITHOUT TIME ZONE,
    last_check_time      TIMESTAMP WITHOUT TIME ZONE,
    original_percentage  DOUBLE PRECISION,
    borrowing_percentage DOUBLE PRECISION,
    citation_percentage  DOUBLE PRECISION,
    check_time           time WITHOUT TIME ZONE,
    report_id            BIGINT,
    CONSTRAINT pk_reports_params PRIMARY KEY (id)
);

CREATE TABLE reports_sources
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_position       BIGINT,
    borrowing_percentage DOUBLE PRECISION,
    end_position         BIGINT,
    url                  VARCHAR(255),
    source_type          VARCHAR(255),
    report_id            BIGINT,
    CONSTRAINT pk_reports_sources PRIMARY KEY (id)
);

ALTER TABLE papers
    ADD CONSTRAINT uc_papers_papers_attributes UNIQUE (papers_attributes_id);

ALTER TABLE papers
    ADD CONSTRAINT uc_papers_report UNIQUE (report_id);

ALTER TABLE reports_params
    ADD CONSTRAINT uc_reports_params_report UNIQUE (report_id);

ALTER TABLE papers
    ADD CONSTRAINT FK_PAPERS_ON_PAPERS_ATTRIBUTES FOREIGN KEY (papers_attributes_id) REFERENCES papers_attributes (id);

ALTER TABLE papers
    ADD CONSTRAINT FK_PAPERS_ON_REPORT FOREIGN KEY (report_id) REFERENCES reports (id);

ALTER TABLE papers_texts
    ADD CONSTRAINT FK_PAPERS_TEXTS_ON_PAPERS FOREIGN KEY (papers_id) REFERENCES papers (id);

CREATE INDEX papers_index ON papers_texts (papers_id);

ALTER TABLE reports_params
    ADD CONSTRAINT FK_REPORTS_PARAMS_ON_REPORT FOREIGN KEY (report_id) REFERENCES reports (id);

ALTER TABLE reports_sources
    ADD CONSTRAINT FK_REPORTS_SOURCES_ON_REPORT FOREIGN KEY (report_id) REFERENCES reports (id);

CREATE TABLE users
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username       VARCHAR(255)                            NOT NULL,
    password       VARCHAR(255)                            NOT NULL,
    email          VARCHAR(255)                            NOT NULL,
    account_status VARCHAR(255)                            NOT NULL,
    activate_code  VARCHAR(255),
    role           VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE INDEX idx_activate_code ON users (activate_code);

CREATE INDEX idx_email ON users (email);

CREATE INDEX idx_username ON users (username);

CREATE TABLE mails
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id      BIGINT,
    text         VARCHAR(255),
    deliver_date TIMESTAMP WITHOUT TIME ZONE,
    status       VARCHAR(255),
    CONSTRAINT pk_mails PRIMARY KEY (id)
);