CREATE TABLE group_group_members
(
    group_id        VARCHAR(255) NOT NULL,
    group_member_id BIGINT       NOT NULL,
    CONSTRAINT pk_group_group_members PRIMARY KEY (group_id, group_member_id)
);

CREATE TABLE group_members
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255)                            NOT NULL,
    email    VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_group_members PRIMARY KEY (id)
);

CREATE TABLE groups
(
    id          VARCHAR(255) NOT NULL,
    name        VARCHAR(255) NOT NULL,
    CONSTRAINT pk_groups PRIMARY KEY (id)
);

ALTER TABLE group_members
    ADD CONSTRAINT uc_group_members_email UNIQUE (email);

ALTER TABLE group_members
    ADD CONSTRAINT uc_group_members_username UNIQUE (username);

ALTER TABLE group_group_members
    ADD CONSTRAINT fk_grogromem_on_group FOREIGN KEY (group_id) REFERENCES groups (id);

ALTER TABLE group_group_members
    ADD CONSTRAINT fk_grogromem_on_user FOREIGN KEY (group_member_id) REFERENCES group_members (id);