CREATE TABLE reports
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type VARCHAR(255),
    name VARCHAR(255),
    CONSTRAINT pk_reports PRIMARY KEY (id)
);

CREATE TABLE reports_params
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created              TIMESTAMP WITHOUT TIME ZONE,
    updated              TIMESTAMP WITHOUT TIME ZONE,
    original_percentage  DOUBLE PRECISION,
    borrowing_percentage DOUBLE PRECISION,
    citation_percentage  DOUBLE PRECISION,
    end_position         BIGINT,
    check_time           time WITHOUT TIME ZONE,
    report_id            BIGINT,
    CONSTRAINT pk_reports_params PRIMARY KEY (id)
);

CREATE TABLE reports_sources
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_position BIGINT,
    end_position   BIGINT,
    url            VARCHAR(255),
    source_type    VARCHAR(255),
    report_id      BIGINT,
    CONSTRAINT pk_reports_sources PRIMARY KEY (id)
);

ALTER TABLE papers
    ADD report_id BIGINT;

ALTER TABLE papers
    ADD CONSTRAINT uc_papers_report UNIQUE (report_id);

ALTER TABLE papers
    ADD CONSTRAINT FK_PAPERS_ON_REPORT FOREIGN KEY (report_id) REFERENCES reports (id);