version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 8080:8080
    networks:
      - postgres-net
    environment:
      - spring.datasource.url=jdbc:postgresql://localhost:5432/antiplagiat
    depends_on:
      - postgresql
    volumes:
      - .m2:/root/.m2

  postgresql:
    image: "postgres:14.15-alpine"
    restart: always
    ports:
      - 5432:5432
    networks:
      - postgres-net
    environment:
      POSTGRES_DATABASE: antiplagiat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_ROOT_PASSWORD: postgres
networks:
  postgres-net: